################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
services:
  db:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: postgres:9.4
    volumes:
    - postgres:/var/lib/postgresql/data
  redis:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: redis:alpine
    volumes:
    - redis:/data
  result:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: academiaonline/example-voting-app:latest-result
  vote:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: academiaonline/example-voting-app:latest-vote
  worker:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
    image: academiaonline/example-voting-app:latest-worker
version: '3.8'
volumes:
  postgres:
  redis:
